# fly.toml app configuration file generated for heidy-backend on 2026-07-10T02:17:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'heidy-backend'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'postgres://postgres@127.0.0.1:5432/heidy_api'
  ECTO_IPV6 = 'false'
  EMBEDDED_POSTGRES = 'true'
  PHX_HOST = 'heidy-backend.fly.dev'
  POOL_SIZE = '8'
  PORT = '4000'

[[mounts]]
  source = 'heidy_data'
  destination = '/data'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/v1/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
